### ISSUE TITLE
大兄弟，你这项目值得鼓励，可是太多东西用别人的了吧

### ISSUE THREAD

**Issue by hewking** [wenhuaijun/SearchPictureTool#1]
下载下来一看，重要的都是第三方的，不过也是值得鼓励的，加油

**Comment by wenhuaijun** [comment]
MD支持库，Rxjava,retrofit,fresco这些开源的大型库是现在做项目的标配，并不是我一个人在用。
而Umeng的Library是用做数据统计的，Bmob的Sdk也是用来当后台数据库，这些是国内开发者做小型开发都会用到的。
其次，其他的库并不是因为我不会写才去用的。我做项目前都是把源码看懂了的，每行代码我都能够理解。我自己也能够去实现。在做快速开发的时候，我朋友封装好的，为什么不能直接拿来用呢，这样既能提高开发效率，又节省时间。在开发的途中还帮朋友做的库找到了很多的bug。谢谢你的鼓励，以后会花更多时间做自己的快速开发库。

**Comment by hewking** [comment]
不是说不能用别人的，而且你能够用rxjava技术也不错了， 你那个 叫jude 的朋友真挺厉害的

**Comment by wenhuaijun** [comment]
我这个app本身做出来也算是给他的MVP快速开发库做个案例Demo，帮他推广他的快速开发框架

**Comment by hewking** [comment]
像这种框架自己团队内部用就可以了，像我们一般不会用，倒是可以合适的修改，最好不要用大而全的 用小而美的
