### ISSUE TITLE
用户反馈的界面没有做好适配问题

### ISSUE THREAD

**Issue by Dreamer206602** [wenhuaijun/SearchPictureTool#3]
我用的是魅族4，用户反馈的界面没有做好适配的问题
![shipei](https://cloud.githubusercontent.com/assets/14008096/14941418/dfb6c882-0fcc-11e6-8082-6b3ca506a91b.jpg)

**Comment by wenhuaijun** [comment]
谢谢您的反馈！等会就修改bug

**Comment by Dreamer206602** [comment]
好的
